# Generated by Django 4.2.8 on 2023-12-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그명')),
                ('tag', models.ManyToManyField(blank=True, to='posts.hashtag', verbose_name='해시태그목록')),
            ],
        ),
    ]
