# Generated by Django 4.2.8 on 2023-12-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posts.hashtag', verbose_name='해시태그목록'),
        ),
    ]
